// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// EnvMappingApplyConfiguration represents an declarative configuration of the EnvMapping type for use
// with apply.
type EnvMappingApplyConfiguration struct {
	Name *string `json:"name,omitempty"`
	Key  *string `json:"key,omitempty"`
}

// EnvMappingApplyConfiguration constructs an declarative configuration of the EnvMapping type for use with
// apply.
func EnvMapping() *EnvMappingApplyConfiguration {
	return &EnvMappingApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *EnvMappingApplyConfiguration) WithName(value string) *EnvMappingApplyConfiguration {
	b.Name = &value
	return b
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *EnvMappingApplyConfiguration) WithKey(value string) *EnvMappingApplyConfiguration {
	b.Key = &value
	return b
}
