// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// ServiceBindingSecretReferenceApplyConfiguration represents an declarative configuration of the ServiceBindingSecretReference type for use
// with apply.
type ServiceBindingSecretReferenceApplyConfiguration struct {
	Name *string `json:"name,omitempty"`
}

// ServiceBindingSecretReferenceApplyConfiguration constructs an declarative configuration of the ServiceBindingSecretReference type for use with
// apply.
func ServiceBindingSecretReference() *ServiceBindingSecretReferenceApplyConfiguration {
	return &ServiceBindingSecretReferenceApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ServiceBindingSecretReferenceApplyConfiguration) WithName(value string) *ServiceBindingSecretReferenceApplyConfiguration {
	b.Name = &value
	return b
}
