// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// ServiceBindingServiceReferenceApplyConfiguration represents an declarative configuration of the ServiceBindingServiceReference type for use
// with apply.
type ServiceBindingServiceReferenceApplyConfiguration struct {
	APIVersion *string `json:"apiVersion,omitempty"`
	Kind       *string `json:"kind,omitempty"`
	Name       *string `json:"name,omitempty"`
}

// ServiceBindingServiceReferenceApplyConfiguration constructs an declarative configuration of the ServiceBindingServiceReference type for use with
// apply.
func ServiceBindingServiceReference() *ServiceBindingServiceReferenceApplyConfiguration {
	return &ServiceBindingServiceReferenceApplyConfiguration{}
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *ServiceBindingServiceReferenceApplyConfiguration) WithAPIVersion(value string) *ServiceBindingServiceReferenceApplyConfiguration {
	b.APIVersion = &value
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *ServiceBindingServiceReferenceApplyConfiguration) WithKind(value string) *ServiceBindingServiceReferenceApplyConfiguration {
	b.Kind = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ServiceBindingServiceReferenceApplyConfiguration) WithName(value string) *ServiceBindingServiceReferenceApplyConfiguration {
	b.Name = &value
	return b
}
