// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// EagerCacheRuleSpecApplyConfiguration represents an declarative configuration of the EagerCacheRuleSpec type for use
// with apply.
type EagerCacheRuleSpecApplyConfiguration struct {
	Cache *CacheServiceApplyConfiguration `json:"cache,omitempty"`
}

// EagerCacheRuleSpecApplyConfiguration constructs an declarative configuration of the EagerCacheRuleSpec type for use with
// apply.
func EagerCacheRuleSpec() *EagerCacheRuleSpecApplyConfiguration {
	return &EagerCacheRuleSpecApplyConfiguration{}
}

// WithCache sets the Cache field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Cache field is set to the value of the last call.
func (b *EagerCacheRuleSpecApplyConfiguration) WithCache(value *CacheServiceApplyConfiguration) *EagerCacheRuleSpecApplyConfiguration {
	b.Cache = value
	return b
}
