// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// CacheServiceApplyConfiguration represents an declarative configuration of the CacheService type for use
// with apply.
type CacheServiceApplyConfiguration struct {
	Name      *string `json:"name,omitempty"`
	Namespace *string `json:"namespace,omitempty"`
}

// CacheServiceApplyConfiguration constructs an declarative configuration of the CacheService type for use with
// apply.
func CacheService() *CacheServiceApplyConfiguration {
	return &CacheServiceApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *CacheServiceApplyConfiguration) WithName(value string) *CacheServiceApplyConfiguration {
	b.Name = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *CacheServiceApplyConfiguration) WithNamespace(value string) *CacheServiceApplyConfiguration {
	b.Namespace = &value
	return b
}
