// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// LazyCacheRuleSpecApplyConfiguration represents an declarative configuration of the LazyCacheRuleSpec type for use
// with apply.
type LazyCacheRuleSpecApplyConfiguration struct {
	Cache *CacheServiceApplyConfiguration `json:"cache,omitempty"`
}

// LazyCacheRuleSpecApplyConfiguration constructs an declarative configuration of the LazyCacheRuleSpec type for use with
// apply.
func LazyCacheRuleSpec() *LazyCacheRuleSpecApplyConfiguration {
	return &LazyCacheRuleSpecApplyConfiguration{}
}

// WithCache sets the Cache field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Cache field is set to the value of the last call.
func (b *LazyCacheRuleSpecApplyConfiguration) WithCache(value *CacheServiceApplyConfiguration) *LazyCacheRuleSpecApplyConfiguration {
	b.Cache = value
	return b
}
