// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// CacheRegionSpecApplyConfiguration represents an declarative configuration of the CacheRegionSpec type for use
// with apply.
type CacheRegionSpecApplyConfiguration struct {
	Foo *string `json:"foo,omitempty"`
}

// CacheRegionSpecApplyConfiguration constructs an declarative configuration of the CacheRegionSpec type for use with
// apply.
func CacheRegionSpec() *CacheRegionSpecApplyConfiguration {
	return &CacheRegionSpecApplyConfiguration{}
}

// WithFoo sets the Foo field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Foo field is set to the value of the last call.
func (b *CacheRegionSpecApplyConfiguration) WithFoo(value string) *CacheRegionSpecApplyConfiguration {
	b.Foo = &value
	return b
}
