// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// BindingPathApplyConfiguration represents an declarative configuration of the BindingPath type for use
// with apply.
type BindingPathApplyConfiguration struct {
	ContainersPath *string `json:"containersPath,omitempty"`
	SecretPath     *string `json:"secretPath,omitempty"`
}

// BindingPathApplyConfiguration constructs an declarative configuration of the BindingPath type for use with
// apply.
func BindingPath() *BindingPathApplyConfiguration {
	return &BindingPathApplyConfiguration{}
}

// WithContainersPath sets the ContainersPath field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ContainersPath field is set to the value of the last call.
func (b *BindingPathApplyConfiguration) WithContainersPath(value string) *BindingPathApplyConfiguration {
	b.ContainersPath = &value
	return b
}

// WithSecretPath sets the SecretPath field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretPath field is set to the value of the last call.
func (b *BindingPathApplyConfiguration) WithSecretPath(value string) *BindingPathApplyConfiguration {
	b.SecretPath = &value
	return b
}
