// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// NamespacedRefApplyConfiguration represents an declarative configuration of the NamespacedRef type for use
// with apply.
type NamespacedRefApplyConfiguration struct {
	RefApplyConfiguration `json:",inline"`
	Namespace             *string `json:"namespace,omitempty"`
}

// NamespacedRefApplyConfiguration constructs an declarative configuration of the NamespacedRef type for use with
// apply.
func NamespacedRef() *NamespacedRefApplyConfiguration {
	return &NamespacedRefApplyConfiguration{}
}

// WithGroup sets the Group field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Group field is set to the value of the last call.
func (b *NamespacedRefApplyConfiguration) WithGroup(value string) *NamespacedRefApplyConfiguration {
	b.Group = &value
	return b
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *NamespacedRefApplyConfiguration) WithVersion(value string) *NamespacedRefApplyConfiguration {
	b.Version = &value
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *NamespacedRefApplyConfiguration) WithKind(value string) *NamespacedRefApplyConfiguration {
	b.Kind = &value
	return b
}

// WithResource sets the Resource field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resource field is set to the value of the last call.
func (b *NamespacedRefApplyConfiguration) WithResource(value string) *NamespacedRefApplyConfiguration {
	b.Resource = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *NamespacedRefApplyConfiguration) WithName(value string) *NamespacedRefApplyConfiguration {
	b.Name = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *NamespacedRefApplyConfiguration) WithNamespace(value string) *NamespacedRefApplyConfiguration {
	b.Namespace = &value
	return b
}
