// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// AlertingSpecApplyConfiguration represents an declarative configuration of the AlertingSpec type for use
// with apply.
type AlertingSpecApplyConfiguration struct {
	Alertmanagers []AlertmanagerEndpointsApplyConfiguration `json:"alertmanagers,omitempty"`
}

// AlertingSpecApplyConfiguration constructs an declarative configuration of the AlertingSpec type for use with
// apply.
func AlertingSpec() *AlertingSpecApplyConfiguration {
	return &AlertingSpecApplyConfiguration{}
}

// WithAlertmanagers adds the given value to the Alertmanagers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Alertmanagers field.
func (b *AlertingSpecApplyConfiguration) WithAlertmanagers(values ...*AlertmanagerEndpointsApplyConfiguration) *AlertingSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAlertmanagers")
		}
		b.Alertmanagers = append(b.Alertmanagers, *values[i])
	}
	return b
}
