// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// ArbitraryFSAccessThroughSMsConfigApplyConfiguration represents an declarative configuration of the ArbitraryFSAccessThroughSMsConfig type for use
// with apply.
type ArbitraryFSAccessThroughSMsConfigApplyConfiguration struct {
	Deny *bool `json:"deny,omitempty"`
}

// ArbitraryFSAccessThroughSMsConfigApplyConfiguration constructs an declarative configuration of the ArbitraryFSAccessThroughSMsConfig type for use with
// apply.
func ArbitraryFSAccessThroughSMsConfig() *ArbitraryFSAccessThroughSMsConfigApplyConfiguration {
	return &ArbitraryFSAccessThroughSMsConfigApplyConfiguration{}
}

// WithDeny sets the Deny field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Deny field is set to the value of the last call.
func (b *ArbitraryFSAccessThroughSMsConfigApplyConfiguration) WithDeny(value bool) *ArbitraryFSAccessThroughSMsConfigApplyConfiguration {
	b.Deny = &value
	return b
}
