// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// AttachMetadataApplyConfiguration represents an declarative configuration of the AttachMetadata type for use
// with apply.
type AttachMetadataApplyConfiguration struct {
	Node *bool `json:"node,omitempty"`
}

// AttachMetadataApplyConfiguration constructs an declarative configuration of the AttachMetadata type for use with
// apply.
func AttachMetadata() *AttachMetadataApplyConfiguration {
	return &AttachMetadataApplyConfiguration{}
}

// WithNode sets the Node field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Node field is set to the value of the last call.
func (b *AttachMetadataApplyConfiguration) WithNode(value bool) *AttachMetadataApplyConfiguration {
	b.Node = &value
	return b
}
