// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// ProbeTargetsApplyConfiguration represents an declarative configuration of the ProbeTargets type for use
// with apply.
type ProbeTargetsApplyConfiguration struct {
	StaticConfig *ProbeTargetStaticConfigApplyConfiguration `json:"staticConfig,omitempty"`
	Ingress      *ProbeTargetIngressApplyConfiguration      `json:"ingress,omitempty"`
}

// ProbeTargetsApplyConfiguration constructs an declarative configuration of the ProbeTargets type for use with
// apply.
func ProbeTargets() *ProbeTargetsApplyConfiguration {
	return &ProbeTargetsApplyConfiguration{}
}

// WithStaticConfig sets the StaticConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StaticConfig field is set to the value of the last call.
func (b *ProbeTargetsApplyConfiguration) WithStaticConfig(value *ProbeTargetStaticConfigApplyConfiguration) *ProbeTargetsApplyConfiguration {
	b.StaticConfig = value
	return b
}

// WithIngress sets the Ingress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ingress field is set to the value of the last call.
func (b *ProbeTargetsApplyConfiguration) WithIngress(value *ProbeTargetIngressApplyConfiguration) *ProbeTargetsApplyConfiguration {
	b.Ingress = value
	return b
}
