// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	v1 "k8s.io/api/core/v1"
)

// SafeAuthorizationApplyConfiguration represents an declarative configuration of the SafeAuthorization type for use
// with apply.
type SafeAuthorizationApplyConfiguration struct {
	Type        *string               `json:"type,omitempty"`
	Credentials *v1.SecretKeySelector `json:"credentials,omitempty"`
}

// SafeAuthorizationApplyConfiguration constructs an declarative configuration of the SafeAuthorization type for use with
// apply.
func SafeAuthorization() *SafeAuthorizationApplyConfiguration {
	return &SafeAuthorizationApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *SafeAuthorizationApplyConfiguration) WithType(value string) *SafeAuthorizationApplyConfiguration {
	b.Type = &value
	return b
}

// WithCredentials sets the Credentials field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Credentials field is set to the value of the last call.
func (b *SafeAuthorizationApplyConfiguration) WithCredentials(value v1.SecretKeySelector) *SafeAuthorizationApplyConfiguration {
	b.Credentials = &value
	return b
}
