// Code generated by protoc-gen-deepcopy. DO NOT EDIT.

package v1alpha1

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using CacheSpec within kubernetes types, where deepcopy-gen is used.
func (in *CacheSpec) DeepCopyInto(out *CacheSpec) {
	p := proto.Clone(in).(*CacheSpec)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheSpec. Required by controller-gen.
func (in *CacheSpec) DeepCopy() *CacheSpec {
	if in == nil {
		return nil
	}
	out := new(CacheSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new CacheSpec. Required by controller-gen.
func (in *CacheSpec) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using CacheDeploymentSpec within kubernetes types, where deepcopy-gen is used.
func (in *CacheDeploymentSpec) DeepCopyInto(out *CacheDeploymentSpec) {
	p := proto.Clone(in).(*CacheDeploymentSpec)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheDeploymentSpec. Required by controller-gen.
func (in *CacheDeploymentSpec) DeepCopy() *CacheDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(CacheDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new CacheDeploymentSpec. Required by controller-gen.
func (in *CacheDeploymentSpec) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DBSyncerDeploymentSpec within kubernetes types, where deepcopy-gen is used.
func (in *DBSyncerDeploymentSpec) DeepCopyInto(out *DBSyncerDeploymentSpec) {
	p := proto.Clone(in).(*DBSyncerDeploymentSpec)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBSyncerDeploymentSpec. Required by controller-gen.
func (in *DBSyncerDeploymentSpec) DeepCopy() *DBSyncerDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(DBSyncerDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DBSyncerDeploymentSpec. Required by controller-gen.
func (in *DBSyncerDeploymentSpec) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Resources within kubernetes types, where deepcopy-gen is used.
func (in *Resources) DeepCopyInto(out *Resources) {
	p := proto.Clone(in).(*Resources)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Resources. Required by controller-gen.
func (in *Resources) DeepCopy() *Resources {
	if in == nil {
		return nil
	}
	out := new(Resources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Resources. Required by controller-gen.
func (in *Resources) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ResourceQuantity within kubernetes types, where deepcopy-gen is used.
func (in *ResourceQuantity) DeepCopyInto(out *ResourceQuantity) {
	p := proto.Clone(in).(*ResourceQuantity)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceQuantity. Required by controller-gen.
func (in *ResourceQuantity) DeepCopy() *ResourceQuantity {
	if in == nil {
		return nil
	}
	out := new(ResourceQuantity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ResourceQuantity. Required by controller-gen.
func (in *ResourceQuantity) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DataSourceSpec within kubernetes types, where deepcopy-gen is used.
func (in *DataSourceSpec) DeepCopyInto(out *DataSourceSpec) {
	p := proto.Clone(in).(*DataSourceSpec)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSourceSpec. Required by controller-gen.
func (in *DataSourceSpec) DeepCopy() *DataSourceSpec {
	if in == nil {
		return nil
	}
	out := new(DataSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DataSourceSpec. Required by controller-gen.
func (in *DataSourceSpec) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using LocalObjectReference within kubernetes types, where deepcopy-gen is used.
func (in *LocalObjectReference) DeepCopyInto(out *LocalObjectReference) {
	p := proto.Clone(in).(*LocalObjectReference)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalObjectReference. Required by controller-gen.
func (in *LocalObjectReference) DeepCopy() *LocalObjectReference {
	if in == nil {
		return nil
	}
	out := new(LocalObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new LocalObjectReference. Required by controller-gen.
func (in *LocalObjectReference) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ServiceRef within kubernetes types, where deepcopy-gen is used.
func (in *ServiceRef) DeepCopyInto(out *ServiceRef) {
	p := proto.Clone(in).(*ServiceRef)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceRef. Required by controller-gen.
func (in *ServiceRef) DeepCopy() *ServiceRef {
	if in == nil {
		return nil
	}
	out := new(ServiceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ServiceRef. Required by controller-gen.
func (in *ServiceRef) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using CacheConf within kubernetes types, where deepcopy-gen is used.
func (in *CacheConf) DeepCopyInto(out *CacheConf) {
	p := proto.Clone(in).(*CacheConf)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheConf. Required by controller-gen.
func (in *CacheConf) DeepCopy() *CacheConf {
	if in == nil {
		return nil
	}
	out := new(CacheConf)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new CacheConf. Required by controller-gen.
func (in *CacheConf) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
