// Code generated by protoc-gen-deepcopy. DO NOT EDIT.

package v1alpha1

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using CacheSpec within kubernetes types, where deepcopy-gen is used.
func (in *CacheSpec) DeepCopyInto(out *CacheSpec) {
	p := proto.Clone(in).(*CacheSpec)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheSpec. Required by controller-gen.
func (in *CacheSpec) DeepCopy() *CacheSpec {
	if in == nil {
		return nil
	}
	out := new(CacheSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new CacheSpec. Required by controller-gen.
func (in *CacheSpec) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using CacheConf within kubernetes types, where deepcopy-gen is used.
func (in *CacheConf) DeepCopyInto(out *CacheConf) {
	p := proto.Clone(in).(*CacheConf)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheConf. Required by controller-gen.
func (in *CacheConf) DeepCopy() *CacheConf {
	if in == nil {
		return nil
	}
	out := new(CacheConf)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new CacheConf. Required by controller-gen.
func (in *CacheConf) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
