// Code generated by protoc-gen-deepcopy. DO NOT EDIT.

package v1alpha1

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using EagerCacheRuleSpec within kubernetes types, where deepcopy-gen is used.
func (in *EagerCacheRuleSpec) DeepCopyInto(out *EagerCacheRuleSpec) {
	p := proto.Clone(in).(*EagerCacheRuleSpec)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EagerCacheRuleSpec. Required by controller-gen.
func (in *EagerCacheRuleSpec) DeepCopy() *EagerCacheRuleSpec {
	if in == nil {
		return nil
	}
	out := new(EagerCacheRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new EagerCacheRuleSpec. Required by controller-gen.
func (in *EagerCacheRuleSpec) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using LazyCacheRuleSpec within kubernetes types, where deepcopy-gen is used.
func (in *LazyCacheRuleSpec) DeepCopyInto(out *LazyCacheRuleSpec) {
	p := proto.Clone(in).(*LazyCacheRuleSpec)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LazyCacheRuleSpec. Required by controller-gen.
func (in *LazyCacheRuleSpec) DeepCopy() *LazyCacheRuleSpec {
	if in == nil {
		return nil
	}
	out := new(LazyCacheRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new LazyCacheRuleSpec. Required by controller-gen.
func (in *LazyCacheRuleSpec) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using LazyCacheKey within kubernetes types, where deepcopy-gen is used.
func (in *LazyCacheKey) DeepCopyInto(out *LazyCacheKey) {
	p := proto.Clone(in).(*LazyCacheKey)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LazyCacheKey. Required by controller-gen.
func (in *LazyCacheKey) DeepCopy() *LazyCacheKey {
	if in == nil {
		return nil
	}
	out := new(LazyCacheKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new LazyCacheKey. Required by controller-gen.
func (in *LazyCacheKey) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using EagerCacheKey within kubernetes types, where deepcopy-gen is used.
func (in *EagerCacheKey) DeepCopyInto(out *EagerCacheKey) {
	p := proto.Clone(in).(*EagerCacheKey)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EagerCacheKey. Required by controller-gen.
func (in *EagerCacheKey) DeepCopy() *EagerCacheKey {
	if in == nil {
		return nil
	}
	out := new(EagerCacheKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new EagerCacheKey. Required by controller-gen.
func (in *EagerCacheKey) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Value within kubernetes types, where deepcopy-gen is used.
func (in *Value) DeepCopyInto(out *Value) {
	p := proto.Clone(in).(*Value)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Value. Required by controller-gen.
func (in *Value) DeepCopy() *Value {
	if in == nil {
		return nil
	}
	out := new(Value)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Value. Required by controller-gen.
func (in *Value) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using NamespacedObjectReference within kubernetes types, where deepcopy-gen is used.
func (in *NamespacedObjectReference) DeepCopyInto(out *NamespacedObjectReference) {
	p := proto.Clone(in).(*NamespacedObjectReference)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedObjectReference. Required by controller-gen.
func (in *NamespacedObjectReference) DeepCopy() *NamespacedObjectReference {
	if in == nil {
		return nil
	}
	out := new(NamespacedObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedObjectReference. Required by controller-gen.
func (in *NamespacedObjectReference) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
