// Code generated by protoc-gen-deepcopy. DO NOT EDIT.

package v1alpha1

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using DataSourceSpec within kubernetes types, where deepcopy-gen is used.
func (in *DataSourceSpec) DeepCopyInto(out *DataSourceSpec) {
	p := proto.Clone(in).(*DataSourceSpec)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSourceSpec. Required by controller-gen.
func (in *DataSourceSpec) DeepCopy() *DataSourceSpec {
	if in == nil {
		return nil
	}
	out := new(DataSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DataSourceSpec. Required by controller-gen.
func (in *DataSourceSpec) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using EagerCacheRuleSpec within kubernetes types, where deepcopy-gen is used.
func (in *EagerCacheRuleSpec) DeepCopyInto(out *EagerCacheRuleSpec) {
	p := proto.Clone(in).(*EagerCacheRuleSpec)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EagerCacheRuleSpec. Required by controller-gen.
func (in *EagerCacheRuleSpec) DeepCopy() *EagerCacheRuleSpec {
	if in == nil {
		return nil
	}
	out := new(EagerCacheRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new EagerCacheRuleSpec. Required by controller-gen.
func (in *EagerCacheRuleSpec) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using LazyCacheRuleSpec within kubernetes types, where deepcopy-gen is used.
func (in *LazyCacheRuleSpec) DeepCopyInto(out *LazyCacheRuleSpec) {
	p := proto.Clone(in).(*LazyCacheRuleSpec)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LazyCacheRuleSpec. Required by controller-gen.
func (in *LazyCacheRuleSpec) DeepCopy() *LazyCacheRuleSpec {
	if in == nil {
		return nil
	}
	out := new(LazyCacheRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new LazyCacheRuleSpec. Required by controller-gen.
func (in *LazyCacheRuleSpec) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Key within kubernetes types, where deepcopy-gen is used.
func (in *Key) DeepCopyInto(out *Key) {
	p := proto.Clone(in).(*Key)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Key. Required by controller-gen.
func (in *Key) DeepCopy() *Key {
	if in == nil {
		return nil
	}
	out := new(Key)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Key. Required by controller-gen.
func (in *Key) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Value within kubernetes types, where deepcopy-gen is used.
func (in *Value) DeepCopyInto(out *Value) {
	p := proto.Clone(in).(*Value)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Value. Required by controller-gen.
func (in *Value) DeepCopy() *Value {
	if in == nil {
		return nil
	}
	out := new(Value)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Value. Required by controller-gen.
func (in *Value) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using NamespacedRef within kubernetes types, where deepcopy-gen is used.
func (in *NamespacedRef) DeepCopyInto(out *NamespacedRef) {
	p := proto.Clone(in).(*NamespacedRef)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedRef. Required by controller-gen.
func (in *NamespacedRef) DeepCopy() *NamespacedRef {
	if in == nil {
		return nil
	}
	out := new(NamespacedRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedRef. Required by controller-gen.
func (in *NamespacedRef) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
