// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/gingersnap-project/operator/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// CacheConditionApplyConfiguration represents an declarative configuration of the CacheCondition type for use
// with apply.
type CacheConditionApplyConfiguration struct {
	Type    *v1alpha1.CacheConditionType `json:"type,omitempty"`
	Status  *v1.ConditionStatus          `json:"status,omitempty"`
	Message *string                      `json:"message,omitempty"`
}

// CacheConditionApplyConfiguration constructs an declarative configuration of the CacheCondition type for use with
// apply.
func CacheCondition() *CacheConditionApplyConfiguration {
	return &CacheConditionApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *CacheConditionApplyConfiguration) WithType(value v1alpha1.CacheConditionType) *CacheConditionApplyConfiguration {
	b.Type = &value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *CacheConditionApplyConfiguration) WithStatus(value v1.ConditionStatus) *CacheConditionApplyConfiguration {
	b.Status = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *CacheConditionApplyConfiguration) WithMessage(value string) *CacheConditionApplyConfiguration {
	b.Message = &value
	return b
}
