// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// NamespacedObjectReferenceApplyConfiguration represents an declarative configuration of the NamespacedObjectReference type for use
// with apply.
type NamespacedObjectReferenceApplyConfiguration struct {
	Name      *string `json:"name,omitempty"`
	Namespace *string `json:"namespace,omitempty"`
}

// NamespacedObjectReferenceApplyConfiguration constructs an declarative configuration of the NamespacedObjectReference type for use with
// apply.
func NamespacedObjectReference() *NamespacedObjectReferenceApplyConfiguration {
	return &NamespacedObjectReferenceApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *NamespacedObjectReferenceApplyConfiguration) WithName(value string) *NamespacedObjectReferenceApplyConfiguration {
	b.Name = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *NamespacedObjectReferenceApplyConfiguration) WithNamespace(value string) *NamespacedObjectReferenceApplyConfiguration {
	b.Namespace = &value
	return b
}
