// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// QuerySpecApplyConfiguration represents an declarative configuration of the QuerySpec type for use
// with apply.
type QuerySpecApplyConfiguration struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// QuerySpecApplyConfiguration constructs an declarative configuration of the QuerySpec type for use with
// apply.
func QuerySpec() *QuerySpecApplyConfiguration {
	return &QuerySpecApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *QuerySpecApplyConfiguration) WithEnabled(value bool) *QuerySpecApplyConfiguration {
	b.Enabled = &value
	return b
}
