// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ResourcesApplyConfiguration represents an declarative configuration of the Resources type for use
// with apply.
type ResourcesApplyConfiguration struct {
	Requests *ResourceQuantityApplyConfiguration `json:"requests,omitempty"`
	Limits   *ResourceQuantityApplyConfiguration `json:"limits,omitempty"`
}

// ResourcesApplyConfiguration constructs an declarative configuration of the Resources type for use with
// apply.
func Resources() *ResourcesApplyConfiguration {
	return &ResourcesApplyConfiguration{}
}

// WithRequests sets the Requests field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Requests field is set to the value of the last call.
func (b *ResourcesApplyConfiguration) WithRequests(value *ResourceQuantityApplyConfiguration) *ResourcesApplyConfiguration {
	b.Requests = value
	return b
}

// WithLimits sets the Limits field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Limits field is set to the value of the last call.
func (b *ResourcesApplyConfiguration) WithLimits(value *ResourceQuantityApplyConfiguration) *ResourcesApplyConfiguration {
	b.Limits = value
	return b
}
