// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ServiceRefApplyConfiguration represents an declarative configuration of the ServiceRef type for use
// with apply.
type ServiceRefApplyConfiguration struct {
	ApiVersion *string `json:"api_version,omitempty"`
	Kind       *string `json:"kind,omitempty"`
	Name       *string `json:"name,omitempty"`
}

// ServiceRefApplyConfiguration constructs an declarative configuration of the ServiceRef type for use with
// apply.
func ServiceRef() *ServiceRefApplyConfiguration {
	return &ServiceRefApplyConfiguration{}
}

// WithApiVersion sets the ApiVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ApiVersion field is set to the value of the last call.
func (b *ServiceRefApplyConfiguration) WithApiVersion(value string) *ServiceRefApplyConfiguration {
	b.ApiVersion = &value
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *ServiceRefApplyConfiguration) WithKind(value string) *ServiceRefApplyConfiguration {
	b.Kind = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ServiceRefApplyConfiguration) WithName(value string) *ServiceRefApplyConfiguration {
	b.Name = &value
	return b
}
