// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/gingersnap-project/operator/api/v1alpha1"
)

// CacheDeploymentSpecApplyConfiguration represents an declarative configuration of the CacheDeploymentSpec type for use
// with apply.
type CacheDeploymentSpecApplyConfiguration struct {
	Type      *v1alpha1.CacheDeploymentType `json:"type,omitempty"`
	Resources *ResourcesApplyConfiguration  `json:"resources,omitempty"`
	Replicas  *int32                        `json:"replicas,omitempty"`
}

// CacheDeploymentSpecApplyConfiguration constructs an declarative configuration of the CacheDeploymentSpec type for use with
// apply.
func CacheDeploymentSpec() *CacheDeploymentSpecApplyConfiguration {
	return &CacheDeploymentSpecApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *CacheDeploymentSpecApplyConfiguration) WithType(value v1alpha1.CacheDeploymentType) *CacheDeploymentSpecApplyConfiguration {
	b.Type = &value
	return b
}

// WithResources sets the Resources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resources field is set to the value of the last call.
func (b *CacheDeploymentSpecApplyConfiguration) WithResources(value *ResourcesApplyConfiguration) *CacheDeploymentSpecApplyConfiguration {
	b.Resources = value
	return b
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *CacheDeploymentSpecApplyConfiguration) WithReplicas(value int32) *CacheDeploymentSpecApplyConfiguration {
	b.Replicas = &value
	return b
}
