// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// CacheSpecApplyConfiguration represents an declarative configuration of the CacheSpec type for use
// with apply.
type CacheSpecApplyConfiguration struct {
	Deployment *CacheDeploymentSpecApplyConfiguration    `json:"deployment,omitempty"`
	DbSyncer   *DBSyncerDeploymentSpecApplyConfiguration `json:"db_syncer,omitempty"`
	DataSource *DataSourceSpecApplyConfiguration         `json:"data_source,omitempty"`
}

// CacheSpecApplyConfiguration constructs an declarative configuration of the CacheSpec type for use with
// apply.
func CacheSpec() *CacheSpecApplyConfiguration {
	return &CacheSpecApplyConfiguration{}
}

// WithDeployment sets the Deployment field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Deployment field is set to the value of the last call.
func (b *CacheSpecApplyConfiguration) WithDeployment(value *CacheDeploymentSpecApplyConfiguration) *CacheSpecApplyConfiguration {
	b.Deployment = value
	return b
}

// WithDbSyncer sets the DbSyncer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DbSyncer field is set to the value of the last call.
func (b *CacheSpecApplyConfiguration) WithDbSyncer(value *DBSyncerDeploymentSpecApplyConfiguration) *CacheSpecApplyConfiguration {
	b.DbSyncer = value
	return b
}

// WithDataSource sets the DataSource field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DataSource field is set to the value of the last call.
func (b *CacheSpecApplyConfiguration) WithDataSource(value *DataSourceSpecApplyConfiguration) *CacheSpecApplyConfiguration {
	b.DataSource = value
	return b
}
