// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// NamespacedRefApplyConfiguration represents an declarative configuration of the NamespacedRef type for use
// with apply.
type NamespacedRefApplyConfiguration struct {
	Name      *string `json:"name,omitempty"`
	Namespace *string `json:"namespace,omitempty"`
}

// NamespacedRefApplyConfiguration constructs an declarative configuration of the NamespacedRef type for use with
// apply.
func NamespacedRef() *NamespacedRefApplyConfiguration {
	return &NamespacedRefApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *NamespacedRefApplyConfiguration) WithName(value string) *NamespacedRefApplyConfiguration {
	b.Name = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *NamespacedRefApplyConfiguration) WithNamespace(value string) *NamespacedRefApplyConfiguration {
	b.Namespace = &value
	return b
}
