// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ServiceBindingApplyConfiguration represents an declarative configuration of the ServiceBinding type for use
// with apply.
type ServiceBindingApplyConfiguration struct {
	Name *string `json:"name,omitempty"`
}

// ServiceBindingApplyConfiguration constructs an declarative configuration of the ServiceBinding type for use with
// apply.
func ServiceBinding() *ServiceBindingApplyConfiguration {
	return &ServiceBindingApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ServiceBindingApplyConfiguration) WithName(value string) *ServiceBindingApplyConfiguration {
	b.Name = &value
	return b
}
