// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ValueApplyConfiguration represents an declarative configuration of the Value type for use
// with apply.
type ValueApplyConfiguration struct {
	ValueColumns []string `json:"valueColumns,omitempty"`
}

// ValueApplyConfiguration constructs an declarative configuration of the Value type for use with
// apply.
func Value() *ValueApplyConfiguration {
	return &ValueApplyConfiguration{}
}

// WithValueColumns adds the given value to the ValueColumns field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ValueColumns field.
func (b *ValueApplyConfiguration) WithValueColumns(values ...string) *ValueApplyConfiguration {
	for i := range values {
		b.ValueColumns = append(b.ValueColumns, values[i])
	}
	return b
}
